### ISSUE TITLE
Role does not have the correct IAM policies during set up

### ISSUE THREAD

**Issue by peteawood** [aws/porting-assistant-dotnet-datastore#3] opened 2020-07-27 16:23 UTC
Hi,

I'm trying to use this application but am getting stuck when selecting a named profile. I have followed the pre-requisites [here](https://docs.aws.amazon.com/portingassistant/latest/userguide/porting-assistant-prerequisites.html) and have added an inline policy to the role my profile is associated with but when clicking Next I just get the error:

 _PortingRole does not have the correct IAM policies. If you need help setting up your profile see Learn more above._

I have also tried creating a Role with the required permission only and then creating a Named Profile which assumes this role through the use of the source_profile and role_arn options in the credentials file. This does not work either.

Other potentially useful information:

The credentials are temporary credentials for my Federated User.
I am behind an authenticated proxy (however my AWS CLI works fine)
I have tried without the proxy and it does not work (although if the tool is a .net app and is configured to pick up the system proxy this might explain the issue)

Many thanks :)

**Comment by sreenaath-amzn** [comment] 2020-07-27 19:01
+aws-porting-assistant-support
Team
Can you look in to this and if need be jump on a working session with the customer?

--regards
sreenaath

**Comment by nshiramshetti** [comment] 2020-07-27 22:06
@peteawood 
Thank you for reporting the issue. To debug further on the issue, could you please verify as mentioned below.

**Able to connect to data store?** 
Run the command:   curl -I "https://s3-us-west-2.amazonaws.com/aws.portingassistant.dotnet.datastore" 
If you are not able to connect to the S3 datastore, please verify your proxy configuration, and try again.

**Able to use AWS credentials?**
Run any AWS command using your credentials:  Example: aws ec2 describe-regions

If you still see the issue, please send us (aws-porting-assistant-support@amazon.com) the logs from location:  "\Users\[USER]\AppData\Roaming\Porting Assistant for .NET\logs"

**Comment by sreenaath-amzn** [comment] 2020-07-27 22:18
Responded to the issue. We shall wait for the response in case he needs a working session.
https://github.com/aws/porting-assistant-dotnet-datastore/issues/3

Thanks,
Nagaraju

From: "Vasudevan, Sreenaath" <sreevasu@amazon.com>
Date: Monday, July 27, 2020 at 12:01 PM
To: aws/porting-assistant-dotnet-datastore <reply@reply.github.com>, aws/porting-assistant-dotnet-datastore <porting-assistant-dotnet-datastore@noreply.github.com>, "aws-porting-assistant-support@amazon.com" <aws-porting-assistant-support@amazon.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [aws/porting-assistant-dotnet-datastore] Role does not have the correct IAM policies during set up (#3)

+aws-porting-assistant-support
Team
Can you look in to this and if need be jump on a working session with the customer?

--regards
sreenaath

**Comment by peteawood** [comment] 2020-07-28 13:38
Hi @nshiramshetti,
 
**Connection to data store**:
```

$ curl -I "https://s3-us-west-2.amazonaws.com/aws.portingassistant.dotnet.datastore"
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
x-amz-id-2: EVd5ZLxXqYN5Gv0Ho72RBZko3RcwwctqQRotm+ImBMPSy/wyGdkcO0V9uhnDaEiZ2sekellLrZQ=
x-amz-request-id: A6BB5A83D821B98C
Date: Tue, 28 Jul 2020 13:13:35 GMT
x-amz-bucket-region: us-west-2
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3
```
**Use of AWS Credentials:**
```
$ aws ec2 describe-regions
{
    "Regions": [
        {
            "Endpoint": "ec2.eu-north-1.amazonaws.com",
            "RegionName": "eu-north-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-south-1.amazonaws.com",
            "RegionName": "ap-south-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-3.amazonaws.com",
            "RegionName": "eu-west-3",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-2.amazonaws.com",
            "RegionName": "eu-west-2",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.eu-west-1.amazonaws.com",
            "RegionName": "eu-west-1",
            "OptInStatus": "opt-in-not-required"
        },
        {
            "Endpoint": "ec2.ap-northeast-2.amazonaws.com",
-- More  --
```

The error still occurs, the logs indicate a possible SSL version error. I will remove identifying information (which **includes Base64 encoded credentials** for anyone else reading this) and email to the address you provided.

Thanks!

**Comment by peteawood** [comment] 2020-07-28 14:07
I suspect the issue is that the tool is picking up my proxy and is able to authenticate okay but is attempting to use https with the proxy (my proxy only supports http). Having checked the logs after disabling the proxy, I can see that the proxy address is still being picked up from somewhere. Are you able to tell me where the tool looks for the proxy settings so I can clear them?

**Comment by nshiramshetti** [comment] 2020-07-29 00:57
We use the settings from IE. Please refer:
https://smartproxy.com/configuration/how-to-setup-proxy-on-internet-explorer-browser

**Comment by jonlouie** [comment] 2020-08-04 19:22
@peteawood Just following up- are you still experiencing this issue?

**Comment by peteawood** [comment] 2020-08-04 19:43
Oh apologies, I thought I had replied already.

Yes I still experienced the error even after clearing system/IE proxy. However when I cleared my HTTP/HTTPS_PROXY environment variables I received a different underlying error (think it was 403) rather than the SSL error. I will reconfirm and get some log output.

**Comment by peteawood** [comment] 2020-08-05 14:41
Yes, I still get this in the app:

_PortingRole does not have the correct IAM policies. If you need help setting up your profile see Learn more above_

In the log I get
```

message: 'Request failed with status code 403',
  name: 'Error',
  stack: 'Error: Request failed with status code 403\n' +
    '    at createError (C:\\Users\\<USER_ID>\\AppData\\Local\\Programs\\Porting Assistant for .NET\\resources\\app.asar\\node_modules\\aws-api-gateway-client\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n' +
    '    at settle (C:\\Users\\<USER_ID>\\AppData\\Local\\Programs\\Porting Assistant for .NET\\resources\\app.asar\\node_modules\\aws-api-gateway-client\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (C:\\Users\\<USER_ID>\\AppData\\Local\\Programs\\Porting Assistant for .NET\\resources\\app.asar\\node_modules\\aws-api-gateway-client\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n' +
    '    at IncomingMessage.emit (events.js:215:7)\n' +
    '    at IncomingMessage.EventEmitter.emit (domain.js:476:20)\n' +
    '    at endReadableNT (_stream_readable.js:1183:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)',
  config: {
    url: 'https://encore-telemetry.us-east-1.amazonaws.com/put-log-data',
    method: 'post',
```
But the above looks more like an issue recording the error rather than with the porting assistant itself.

For info, I can still connect to https://s3-us-west-2.amazonaws.com/aws.portingassistant.dotnet.datastore via my browser or curl even with my HTTP_PROXY environment variables cleared and the system/IE proxy cleared.

**Comment by jonlouie** [comment] 2020-08-05 18:27
@peteawood Thank you for sharing that additional information; we're currently looking into the cause of the error.

Do you recall if you consented to AWS metrics within Porting Assistant? If so, would you be able to send the relevant AWS Account ID to our customer support email at aws-porting-assistant-support@amazon.com?

**Comment by peteawood** [comment] 2020-08-07 14:47
@jonlouie - I tried it both with and without consent and saw the same error in the log. Have sent the account id :)

**Comment by jonlouie** [comment] 2020-08-11 16:34
@peteawood Thank you for sharing your account id with us. We were able to replicate your experience by using federated credentials which is not something we support right now. Would it be possible to try again using permanent credentials?

**Comment by peteawood** [comment] 2020-08-25 10:08
@jonlouie I tried using a permanent user and I got the same original error until I removed the proxy from the equation (had to delete HTTP_PROXY and HTTPS_PROXY environment variables). I get a subsequent error during analysis but that should be a separate ticket.

So in summary, I accept that federated credentials are not currently supported and that permanent credentials work. However the proxy support which is present in the app doesn't work, indicated by the SSL version error mentioned in https://github.com/aws/porting-assistant-dotnet-datastore/issues/3#issuecomment-665045877 (and in the logs emailed) due to, I believe, what I mentioned in https://github.com/aws/porting-assistant-dotnet-datastore/issues/3#issuecomment-665061459.

**Comment by jonlouie** [comment] 2020-09-08 22:27
@peteawood We are starting to look into the proxy issue you mentioned above. Would you be able to share details about your proxy config with our support email at aws-porting-assistant-support@amazon.com? And if you still happen to have the logs displaying the SSL version error, would you mind including that as well? I don't believe our team ever received the initial email (at no fault of yours). We appreciate your patience and willingness to work with us on these issues!

**Comment by peteawood** [comment] 2020-09-23 08:44
@jonlouie - I have emailed the log and proxy details again :)

**Comment by jonlouie** [comment] 2020-09-23 17:16
@peteawood Thank you for sending the information once more. Our team has received it, and we are looking into the issue.

**Comment by flywanli** [comment] 2020-10-19 22:55
@peteawood, thanks for your feedback. Unfortunately, we don’t support http currently. We are taking this request as a new feature in our future plan. I will close this ticket now, If there is still problem with this ticket, we will reopen it. Thanks!

**Closed by flywanli** 2020-10-19 22:55 UTC

**Comment by Nikita-T86** [comment] 2021-01-18 11:16
I have similar problem - I am federated user behind the proxy and got error "default does not have the correct IAM policies. If you need help setting up your profile see Learn more above." with 403 error in logs. Any updates to support federated users?

In addition, when I click on "Add a named profile" for a moment I see the form with fields to enter but it immediately disappears and I got empty white screen in app window.

**Comment by huawenm** [comment] 2021-01-18 19:53
Hi Nikita-T86,

Thank you for reporting the issue. Unfortunately, we are still need IAM name profile to use porting assistant for now, federated user is not supported.  

We apologize for the issue you got on "Add a named profile",  we will fix that issue ASAP.

For now if you have an AWS account, you can setup a named profile through aws cli , then reopen the porting assistant app. by default the profile will be setup .
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

If you still have trouble to access porting assistant, please feel free to reach us at aws-porting-assistant-support@amazon.com.  We will keep you updated for the fix for "Add a named profile" .
