### ISSUE TITLE
nunit 3.12 deprecated?

### ISSUE THREAD

**Issue by aleksandrov** [aws/porting-assistant-dotnet-datastore#1] opened 2020-07-03 08:20 UTC
Could you point me how to trace why porting assistant says that Nunit 3.12 is deprecated? It is latest version available and it supports .NET Core.

**Comment by nshiramshetti** [comment] 2020-07-06 22:46
Thank you @aleksandrov  for using the tool and reporting the issue.

Based on the data file we created for NUnit package, it is compatible with 3.12.0. 

Could you please give us more details to find out the root cause of the issue. Please send us the screenshot of the error to  
aws-porting-assistant-support@amazon.com ? 
AWS engineering team will be more than happy to setup sometime with you to debug this issue.

Data file for NUnit package:
```
 "Name": "NUnit",
        "Targets": {
            "netcoreapp3.1": [
                "3.9.0",
                "3.8.1",
                "3.8.0",
                "3.7.1",
                "3.7.0",
                "3.6.1",
                "3.6.0",
                "3.12.0",
                "3.11.0",
                "3.10.1",
                "3.10.0"
            ],
            "netstandard1.3": [
                "3.9.0",
                "3.8.1",
                "3.8.0",
                "3.7.1",
                "3.7.0"
            ],
            "netstandard2.0": [
                "3.12.0",
                "3.11.0",
                "3.10.1",
                "3.10.0"
            ]
        },
```

**Comment by aleksandrov** [comment] 2020-07-07 08:27
Screenshot emailed

**Comment by nshiramshetti** [comment] 2020-07-08 00:35
@aleksandrov We did not receive any email from you. Could you please verify it or resend it.
 However, we have verified at our end with a test solution.


![image](https://user-images.githubusercontent.com/67487540/86859643-f3137000-c077-11ea-8969-bed44e5ce054.png)

**Comment by aleksandrov** [comment] 2020-07-10 05:40
Sent it again. But as fat as I see it stopped reproducing now.

**Comment by freeranger** [comment] 2020-07-10 06:53
@nshiramshetti  I get this issue too:
![image](https://user-images.githubusercontent.com/1401069/87125401-5c66cf00-c282-11ea-8a2c-eb2e2ce8aa6c.png)
The project targets .NETFramework 4.7.2, .NETCoreApp 2.1.0, .NETCoreApp 3.1.0 - I don't know if that makes a difference?

**Comment by nshiramshetti** [comment] 2020-07-10 23:47
`Nunit 3.12`  package is compatible.
`nunit.framework` package has been deprecated.  https://www.nuget.org/packages/nunit.framework

**Comment by nshiramshetti** [comment] 2020-07-14 03:31
We found an issue with NUnit package. We will resolve the issue and let you know.
Thanks @aleksandrov   again for reporting the problem.

**Comment by mrlloyd-amzn** [comment] 2020-09-28 22:07
Closing issue here. it looks like nunit.framework is the one that is marked as deprecated which is the case from Nuget.

**Closed by mrlloyd-amzn** 2020-09-28 22:07 UTC
