### ISSUE TITLE
No results in assessment list

### ISSUE THREAD

**Issue by poserdonut** [aws/porting-assistant-dotnet-datastore#2] opened 2020-07-04 16:17 UTC
Hi! 

I tried to use this application, however when I choose a solution to assess it seems it starts doing something because I see some processes start and they are using the computers resources. 

However, the list of assessed solutions stays empty. If I try to assess the same solution again the application says the solution is already added. 

I have tried multiple solutions with the same result, sometimes I get a notification about not all nuget packages can be assessed but the list stays empty.

**Comment by sreenaath-amzn** [comment] 2020-07-06 22:32
Hi poserdonut 
Thanks for using the tool. Did you have the right AWS Profile credentials to use the tool? https://docs.aws.amazon.com/portingassistant/latest/userguide/porting-assistant-prerequisites.html
Do you mind sharing more details like the application used, the attached AWS Policy and the error you are running in to to aws-porting-assistant-support@amazon.com ? AWS engineering team will be more than happy to setup sometime with you to debug this issue.

**Comment by poserdonut** [comment] 2020-07-10 08:56
I'm currently on

**Comment by poserdonut** [comment] 2020-07-10 08:57
I'm currently on vacation, I will get back with information when I'm back to work.

**Comment by jonlouie** [comment] 2020-08-04 19:24
Hi @poserdonut, just wanted to follow up- are you still experiencing this issue?

**Comment by poserdonut** [comment] 2020-08-04 19:43
Believe it or not but I am still on vacation so can't verify yet. Sorry.

**Comment by poserdonut** [comment] 2020-08-11 05:53
I have followed the prerequisites. 

The following policy is applied:
![image](https://user-images.githubusercontent.com/61051475/89862097-84aa5c00-dba7-11ea-8be4-aadc7b691435.png)

Now I get an information popup regarding nuget, but the list of projects is still empty.
![image](https://user-images.githubusercontent.com/61051475/89862162-ab689280-dba7-11ea-94ee-436dcd29e615.png)

**Comment by flywanli** [comment] 2020-08-25 20:08
Hi @poserdonut, thanks for attaching the sreenshots. Unfortunately, we still cannot be able to pinpoint the root cause of of case. Would you like to set a session with our AWS engineer in Porting Assistant for .NET team. You can send a email to aws-porting-assistant-support@amazon.com, I'd like to assistant you there.

**Comment by mrlloyd-amzn** [comment] 2020-10-06 18:38
@poserdonut We just released a new version that should address the issue you saw. I am going to close this issue. Please reopen if you still see the issue.

**Closed by mrlloyd-amzn** 2020-10-06 18:38 UTC
