### ISSUE TITLE
Fails to build some projects in solution

### ISSUE THREAD

**Issue by mrahl** [aws/porting-assistant-dotnet-datastore#4] opened 2020-08-03 14:23 UTC
Some projects in the soloution I'm trying trying to analyze fail to build, and I get a notification "Failed to build 14 projects in x.sln" (in total the solution has 64 projects). The solution builds fine in Visual studio (and on our build servers etc, using MSBuild). The projects that fail seem to be the ones that have dependencies on nuget packages in our own feed (not on nuget.org)

How do I configure the available nuget feeds for the porting assistant?

I have tried to add our feed to the solution level .nuget/nuget.config file but that doesn't make any difference. In VS the feeds are configured in the package manager settings so it has no problem locating the feed when building/restoring. Building in VS first to get all packages restored does not help, I get the same error in the porting assistant even though everything is already restored.

All the projects that are failing are using the project SDK format with PackageReference elements.

**Comment by jonlouie** [comment] 2020-08-03 21:35
Hi @mrahl, thank you for reaching out to us. We are currently investigating this scenario. In the meantime, can you try restoring all nuget packages to your project first and then try running the Porting Assistant analysis?

**Comment by jonlouie** [comment] 2020-08-04 19:53
Hi @mrahl, thank you for trying Porting Assistant and reporting this issue. 

On our end, we were not able to replicate the build error using a private nuget feed. If projects are restored prior to the assessment, the expected behavior is for the projects to build successfully. Since this was already attempted, we will try viewing any build errors from the logs.

Do you recall if you consented to AWS metrics? If so, would you be able to send the relevant AWS Account ID to our customer support email at aws-porting-assistant-support@amazon.com?

**Comment by mrahl** [comment] 2020-08-10 06:36
@jonlouie Thanks, I'll reach out via email.

**Comment by PriyamChokhani** [comment] 2020-08-24 06:25
@jonlouie  Thanks. Dropped an email with details.

**Comment by jonlouie** [comment] 2020-08-24 17:17
@PriyamChokhani Thank you for reaching out with that information. We noticed the build errors were from .vbproj assessment which we do not support at this time. Please see this [user guide](https://docs.aws.amazon.com/portingassistant/latest/userguide/what-is-porting-assistant.html) for more information on what is supported by .NET Porting Assistant.

**Comment by jonlouie** [comment] 2020-08-24 17:18
@mrahl For some reason our team did not receive your email containing your account id. Would you mind resending us that information one more time?

**Comment by PriyamChokhani** [comment] 2020-08-25 03:49
Thanks for the info @jonlouie . Do let us know if there is a plan around .vbproj as well.

**Comment by mrahl** [comment] 2020-08-25 06:23
@jonlouie I sent it again now.

**Comment by jonlouie** [comment] 2020-08-26 06:27
Our team has investigated the issues reported here and found that environment variables in nuget config files are interpreted as string literals instead of being substituted for their assigned values, leading to build failures. A fix for this issue is currently under way and is scheduled for our next release.

Another source of build failures is attempting to assess .vbproj files, something we do not support at this time. Additional information regarding what is supported can be found in our [user guide](https://docs.aws.amazon.com/portingassistant/latest/userguide/what-is-porting-assistant.html).

**Comment by mrlloyd-amzn** [comment] 2020-10-06 18:41
We just released version 1.0.2 which should address the issues above. Going to close this out. Please reopen if you still see the issue while running the latest release.

**Closed by mrlloyd-amzn** 2020-10-06 18:41 UTC
